---
title: Premise
author: Kambiz Tavabi
date: '2021-02-10'
slug: []
categories: []
tags: []
draft: yes
---

**If the language of the universe is mathematics, then we humans are
mathematics.**

This eve of Sir Isaac Newton's birth 4 centuries passed,
_homo sapiens_ is by Nobel accounts a simple kind of additive noise
and binary math. I'll leave the additive noise bit to the statisticians and
geneticists to hash out. A wise geneticist once said that the path to
immortality is riddled with exotic diseases and cancer.

So how do we get there?
Let us presume for each _homo_ in the class _sapien_ a purely theoretical limit
from 1 to 0. For said limit, genomics tells us that the
individual human embryo is biologically female at time-zero until a host of conditions are met. For better or worse, the ontogenetic conditional on gender is the Y-chromosome's downstream effects in the mammalian line. So, before we reiterate on
Roe vs. Wade, let's just take a moment to consider the full ramifications of gender itself as a hypothesis before
defining the spectrum.

From a purely _selfish_ perspective, a set of things, in this case, the human
genome, with _apriori_ odds of 1/23, is by way of Bayes law a conditional
probability that has remained stable for at least 2020 years -- give or take. If for no other reason,
then for the rise and fall of human civilizations in perpetuity. Then 1/23 odds
provide a likelihood(null)=(23/7.8e9)^23(1/23).

It's zero. Go ahead and do the math if you don't believe me. So, what is the
point of gender? Sexual reproduction? On this Fri Dec 25
2020 11:30 UTC a zero chance in hell of arbitrating a right to life is morphic
harmony. Nevertheless, by well-known principles of mammalian embryology, an
_a priori_ condition does exist. In the given cascade of genomic stochasticism,
this little likelihood gives rise to a not only spectrum of human genders before us today
but also viable asexual class species on this planet. But in the mammalian case,
this 1/23 odd gives rise to an entire cascade of events that gives rise to gender dimorphism. And my little thought
experiment here is that if we consider gender a spectrum, let us
define that spectrum between some arbitrary numbers [1, -1]. Note, the space of
real numbers between [-1, 1] is infinite, and the limit as mentioned above and inside
the comforts of a unit sphere is, by hypothesis, the _fluid_ magnitude of general
intelligence [g]<sup>1</sup> for a given connectome (ψ).

> 1. Posner, M. I., & Barbey, A. K. (2020). General intelligence in the age of neuroimaging. Trends in Neuroscience and Education, 18, [100126]. https://doi.org/10.1016/j.tine.2020.100126


